Rails 8, handle streaming, custom cdn, url
rkwap/active_storage_bunny pull request #2
Opened 2024-11-28 05:11 UTC by bendangelo

2024-12-10 18:53 UTC, rkwap commented
@bendangelo Thanks for raising the PR and making lot of changes. Apologies for the delay, and due to my busy schedule this week, I will be closing it this weekend.

2024-12-11 16:21 UTC, bendangelo commented
No problem. Take a look at the other pr I opened as well.

2024-12-26 06:46 UTC, rkwap requested changes
Minor refactoring. Rest LGTM!

2024-12-26 06:46 UTC, rkwap commented on lib/active_storage/service/bunny_service.rb
>      attr_reader :client
make base_url as a reader method to keep consistency with `ActiveStorage::Service` abstract class or any implemented class like `ActiveStorage::Service::S3Service`

2024-12-26 06:46 UTC, rkwap commented on lib/active_storage/service/bunny_service.rb
> +          io
```suggestion
          io.set_encoding(Encoding::BINARY)
```

2024-12-26 06:46 UTC, rkwap commented on lib/active_storage/service/bunny_service.rb
> +      File.join(@base_url, key)
```suggestion
      File.join(base_url, key)
```

2024-12-26 06:46 UTC, rkwap commented on lib/active_storage/service/bunny_service.rb
> +          io
better to move this to another private method since it is being used again in stream.

2024-12-26 06:48 UTC, rkwap commented
Do test out after making changes and leave a comment. Will merge ASAP when ready.

2024-12-26 18:53 UTC, bendangelo commented
Done

2024-12-31 04:55 UTC, rkwap commented
Thank you for your contribution :)
merging!

2024-12-31 04:55 UTC, merged